name: PostgreSQL Integration Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
   integration-tests:
    name: PG${{ matrix.postgres-version }}
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
          - 14
          - 15
          - 16
          - 17
          - 18
    uses: ./.github/workflows/pharo-postgres-integration-test.yml
    with:
      postgres-version: ${{ matrix.postgres-version }}
