name: SQLite3 Integration Tests

on: [push,pull_request,workflow_dispatch]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-10, Pharo64-9.0 ]
        rdbms: [ SQLite3 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Install SQLite3
        run: ./scripts/install-SQLite3.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/.unit-tests.ston
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RDBMS: ${{ matrix.rdbms }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: ${{matrix.rdbms}}-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
