name: SQLite3 Integration Tests

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0, Pharo64-7.0 ]
        rdbms: [ SQLite3 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v2
      - uses: ba-st-actions/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Install SQLite3
        run: ./scripts/install-SQLite3.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
        env:
          RDBMS: ${{ matrix.rdbms }}
      - run: echo "::set-env name=SCI_COVERAGE_FILE_LOCATION::${HOME}/.smalltalkCI/_builds/coveralls_results.json"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.SCI_COVERAGE_FILE_LOCATION }}
